- partitions.html.md
RabbitMQ has a new behaviour for clustering and dealing with network partitions. The following documentation is for that. I have also updated the layout repo to include this page in the menu, [this is the pull request](https://github.com/pivotal-cf/docs-layout-repo/pull/27)
[#118828025]
> Document new clustering behaviour (pause_minority)

- install-config-pp.html.md.erb
Hi. 
This is an amendment to the docs to be explicit that we do not support changing IP addresses of existing deployments.   Please can this be applied across all of the live docs. 
Thanks, 
Dave
> updated to warn that changing the ips is not supported

- monitor.html.md.erb
- releases.html.md.erb
In the upcoming release of 1.10 (and 1.9 will also follow) we are changing the prefix we emit metrics for on-demand instances, from `p.rabbitmq` to `p-rabbitmq`. 
Changing the prefix I changed the header of some tables from using `.` as metric separator to `/` to avoid confusion. A similar intervention can be required in the pre provisioned equivalent section
I updated all the references in the monitoring and add a new feature (it was already missing from the known issues).
> Metrics prefix change - 1.10.x

- operations.html.md.erb
This updates the ops section to add how to manually backup rmq and how to check the cluster is healthy before upgrading.
> update the ops section for backups and pre-upgrade checks

- monitor-pp.html.md.erb
- monitor.html.md.erb
* This metric indicates when the disk free alarm has gone off.
[#151851504]
> Update docs to include new disk_free_alarm metric

- monitor-pp.html.md.erb
- monitor.html.md.erb
Hi Docs Team,
the code is not yet in the product. So we can't publish this doc yet, only after cutting the new version of the product.
Let's sync when we would like to publish a new version of 1.9 doc.
thank you,
Alberto
> Update docs to include new disk_free memory alarm metrics

- index.html.md.erb
- releases.html.md.erb
[#152344861]
This is ready to be published at 1.10.5 has been made GA. Also, please let us know if this structure for release notes in 1.10 works for you going forward.
Signed-off-by: Scott Muc <smuc@pivotal.io>
> Release notes for 1.10.5

- deploying.html.md.erb
Fixes to the typo, i.e replace "minium" to minimum
> Fixes typo to the file "deploying.html.md.erb"

- install-config.html.md.erb
- ondemand.html.md.erb
* In PCF 2.0 we have added a feature that will pre-configure `RabbitMQ
VM Type` and `Persistent Disk Type` resources for On Demand Services.
* We describe what the default values are on a fresh installation on PCF
2.0
* We say this feature is only for PCF 2.0 and later
* This is for our 1.11 tile.
> [1.11 tile] Describe pre-configured resources

- upgrade.html.md.erb
- the link was pointing to the landing page, where we have no
information about upgrade paths
- we are using a pivnet link where that information can be found
- we removed references to old tile versions
> 151852562 fix upgrade paths link

- index.html.md.erb
- releases.html.md.erb
In fact 1.7.33 (and 32) had minor issues we captured before releasing. This is
why we will go from 1.7.31 to 1.7.34.
[#153556159]
> Add release notes for 1.7.34

- index.html.md.erb
- releases.html.md.erb
We found minor issues with 1.8.22-24, that's why we are jumping from
1.8.21 to 1.8.25.
[#153556128]
> Add release notes for 1.8.25

- managing.html.md.erb
HAproxy stats dashboard was removed in #151391329.
[#154047675]
> Remove insctructions to enable HAproxy dashboard

- managing.html.md.erb
HAproxy stats dashboard was removed in #151391329.
[#154047675]
> Remove instructions to enable HAproxy dashboard

- index.html.md.erb
Remove co-located errands from feature list in pre-provisioned as it is no longer shipped in the product.
> Removed co-located errands mention from features

- releases.html.md.erb
* This was fixed in 1.9.17
[#155703661]
> Remove fixed known_issue

- ondemand.html.md.erb
Hello docs team,
we have introduced new on-demand plans using RabbitMQ Server 3.7. This PR updates our docs to mention that.We're deprecating 3.6 on-demand plans as well.
[#155892937]
> Introduce on demand 3.7 plans

- releases.html.md.erb
- 1.8.33 was not released as it did not contain the 3421.44 stemcell
[#156347203]
> Update release notes for 1.8.34

- releases.html.md.erb
- upgrade.html.md.erb
Add information for operators to delete On-Demand service instances before upgrading to 1.13
* Include instructions on how to search for existing on-demand instances
[#156169807]
> Operator must ensure there's no on-demand service instance running before bumping to 1.13

- releases.html.md.erb
Hi docs team,
we noticed that we have an invalid link for pivotal-cf page. Our 1.12 product is not compatible with PCF 1.11, but 2.0 and 2.1.
Co-authored-by: Rosie Bloxsom <rbloxsom@pivotal.io>
> Fix link for PCF "Managing Errands" page

- install-config.html.md.erb
@murphe5 can you please review the location of this?
docs team - could we please also add this same commit to this page: https://docs.pivotal.io/rabbitmq-cf/1-13/install-config-pp.html in the same place
This change should probably be backported
> Add production checklist from RMQ OS docs

- releases.html.md.erb
Note that HTTPS has been used outside of the PCF network for a while.  This change would not be easily observable by a customer.
[#158489613]
> Initial release notes for v1.14

- releases.html.md.erb
Change the warning - making it informational and about 2.2.6+
Add known issues to all patches saying dont upgrade on 2.2.0-2.2.5
> Indicate upgrade compatibility with 2.2.6+

- releases.html.md.erb
Just a note for operators that they can still see compilation even though we use compiled releases now
[#158975911]
> Add a note about compilation despite compiled releases

- install-config.html.md.erb
[#161476735]
This fix applies to previous versions too and should be cherry-picked.  Would you like me to submit PRs for that?
Note that the sharding and consistent_hash_exchange plugins are not enabled for v1.14 or earlier.
> STOMP and MQTT not enabled for dedicated instances

- upgrade.html.md.erb
Hey docs team :). 
This change is relevant to all supported versions of the tile. Would you like us to create PR's for all the additional branches?
- When upgrading people want to know if they need to do anything on the
client side
- We added a link to the rabbitmq docs to inform them what to do
[#153211541]
Co-authored-by: Daniil Fedotov <hairyhum@pivotal.io>
> Mention client reconnects

- releases.html.md.erb
Latest 1.14 doesn't emit metrics to the firehose
> Add info about a known issue

- install-config-pp.html.md.erb
- monitor-pp.html.md.erb
- monitor.html.md.erb
- ondemand.html.md.erb
The key information added is that service metrics can be disabled by setting the "Metrics Polling Interval" to -1.
> Document disabling service metrics

- upgrade.html.md.erb
Adding an additional upgrade step to verify the contents of `nodes_running_at_shutdown`. Linked to a Knowledge Base article with instructions on how to proceed if the contents of this file are not as expected.
> Extra upgrade step from 1.12 to 1.13

- use.html.md.erb
[#164380997]
Some example bindings in the docs still had IP addresses in the URIs, instead of the new BOSH DNS names. This commit replaces those dummy IPs with dummy DNS names instead.
Follow on to https://github.com/pivotal-cf/docs-rabbitmq-pcf/pull/387.
> Replaced example binding RMQ IPs with BOSH DNS names

- use.html.md.erb
Previously, enabling TLS required a user to create a service key in
order to find the hostname of the RMQ instance. As of V1.16, this is no
longer the case: users need only provide the command-line args '"tls":
true'.
This arg can also now be provided when the service is created, not just
on service update. This commit fixes the docs to better represent this
change.
[#164380997]
> Update TLS Docs to represent new TLS enable command

- ondemand.html.md.erb
Can we please remove 3.6 references in 1.13-1.16 docs? These were removed in 1.13. Thanks
> Remove 3.6 references

- use.html.md.erb
- vcap-services.html.md.erb
A handful of bindings still had IP addresses in their hostname & uri
parameters.
[#164380997]
Co-authored-by: James McNeil <jmcneil@pivotal.io>
> [on-demand] Replaced instances of IPs with DNS names

- install-config.html.md.erb
STOMP is coming to on-demand only in the unreleased 1.17+, so feel free to merge to master.
[#163418873]
> Added docs for disabling/enabling STOMP plugin in on-demand

- releases.html.md.erb
Hi team, please cherry pick this to all the 1.14 and 1.16 release notes.
> SI sharing for PP enabled via on-demand

- releases.html.md.erb
This is a minor change that we want to add to a previously released patch. We would like to support upgrade from 1.15.* to 1.17.*. However, due to a bug this is not possible for specifically 1.17.0, so we added it as known issue.
Note that in the newly released patch (which is 1.17.1) this is not a problem.
Thanks!
@nodo & @coro
> 1.17.0 known issue

- releases.html.md.erb
Removed 'Known Issue' claiming Management UI is still not accessible.
[#168167710]
> Remove contradiction in 1.16.5 release notes

- releases.html.md.erb
Removed 'Known Issue' claiming Management UI is still not accessible.
[#168167710]
> Remove contradiction in 1.17.1 release notes

- use.html.md.erb
* Correct plan name to `OFF-PLATFORM-PLAN` in off-platform Dev guide
* Advise devs to contact operator if they are unsure about which plans are off-platform
> Fixes to the off-platform developer guide

- install-config.html.md.erb
Removed any mention of the limit in our documentation.
This change *only* applies to v1.18 of the tile, and does not need backporting.
Thanks!
cc @gregttn
> The tile now does not have an upper limit for service instance quota

- off-platform-access.html.md.erb
- use.html.md.erb
Hey docs, this change applies only to version 1.18 of the RMQ tile docs.
cc @gregttn
> Add note about regenerating service keys when off-platform is re-enabled

- releases.html.md.erb
* v1.17.2 will remain unreleased - removed any documentation associated
with it
* v1.17.3 will be released in its stead, at the same time as v1.15.13 &
1.16.6
* Clarified some expectations regarding downtime & cluster shutdown when
upgrading to v1.17.3, vs v1.17.0/v1.17.1.
* 'app downtime' is actually 'cluster downtime'
Please make this live at the same time as 1.15.13 & 1.16.6, once we tell you they are released.
> 1.17.3 release notes - REPLACING 1.17.2 RELEASE NOTES

- prepare-tls.html.md.erb
Can this please be applied to 1.16 and 1.17
Add note to make sure operators are aware of the need to apply changes to PAS when preparing for TLS.
Co-authored-by: David O'Sullivan <daosullivan@pivotal.io>
> Add note to warn operators about PAS update

- index.html.md.erb
- releases.html.md.erb
Also add to release notes that 1.17.1 and above support PCF v2.7. Reference: https://www.pivotaltracker.com/story/show/168191486
> Add 1.17.4 release notes

- releases.html.md.erb
1.18.1 is no longer being released, so remove notes.
We plan on releasing 1.18.2 today; is it possible for this to be merged today? Thanks! :)
> Add release notes for 1.18.2

- about.html.md.erb
- install-config-pp.html.md.erb
We noticed a few things incorrect with our docs. We will cherry-pick to the other supported branches.
> Clarify docs around Management over TLS for 1.16

- index.html.md.erb
- releases.html.md.erb
Please do not publish the docs yet.
Also, please note that PAS compatibility for 2.4 has been removed. Please could you update the compatibility matrix to reflect the same?
Thank you!
> Add 1.16.8 release notes

- index.html.md.erb
- releases.html.md.erb
Please do not publish the docs yet.
Also, please note that PAS compatibility for 2.4 has been removed, and 2.8 has been added! Please could you update the compatibility matrix to reflect the same?
Thank you!
> Add 1.17.5 release notes

- releases.html.md.erb
We missed mentioning this change. This issue was fixed in 1.18.5, this needs to be deployed to prod.
> 1.18.5 release notes - Cluster name change

- releases.html.md.erb
[#173565338]
Co-authored-by: Grzegorz Tatarzyn <gtatarzyn@pivotal.io>
This known_issue should also be added to 1.18.6 and 1.19.0
> Add cluster_name queue issue to known_issues

- enable-oauth.html.md.erb
The UAA group must contain either the RabbitMQ tag `monitoring` or `administrator`.
Also, add a warning that enabling OAuth does not enforce OAuth.
[#174005628]
> Update valid RabbitMQ Tags

- enable-oauth.html.md.erb
Rotating the JWT signing key directly via the UAA API as described in https://docs.cloudfoundry.org/api/uaa/version/74.23.0/index.html#updating-an-identity-zone is currently not supported.
No.
See also https://www.pivotaltracker.com/story/show/173607084
> Add JWT signing key rotation warning

- managing.html.md.erb
Hi docs!
While I was reviewing the OAuth docs for 1.20, I noticed that accessing the management dashboard using the OAuth flow had not been documented. I have added some documentation, please feel free to edit this.
Please merge this into master and 1.20
Best,
Mirah
> Document accessing management UI with OAuth enabled.

- releases.html.md.erb
Hi docs! 
The release notes for 1.20.0 ended up listing incorrect version numbers and this is causing our customers confusion. If we could get these new docs live, we would appreciate it. 
Thanks,
Mirah
> Correct version numbers in release notes.

- enable-oauth.html.md.erb
Yes, to 1.20 please
Having the group name only (instead of DN) results in `Login failed`.
> Fix Distinguished Name description

- enable-oauth.html.md.erb
Hi docs team,
This is a clarification around the uaa commands required for OAuth in the case UAA is configured with a SAML IdP.
Please also cherry-pick this commit back to the 1.20 branch. 
Thanks!
> Separate LDAP and SAML group mapping commands for OAuth.

- releases.html.md.erb
The git source code repository has already been renamed
Tanzu RabbitMQ for VMs story reference: https://www.pivotaltracker.com/story/show/175198324
> Rename cf-rabbitmq-service-gateway-release to cf-service-gateway-release

- about.html.md.erb
- index.html.md.erb
- install-config.html.md.erb
- reference.html.md.erb
- releases.html.md.erb
- service-gateway-access.html.md.erb
- vcap-services.html.md.erb
[#175286350]
None. This is a 1.21 feature.
> Web STOMP support in 1.21

- monitor.html.md.erb
We don't "supporting enabling" the prometheus plugin - since 1.19 we always enable it and don't allow to disable it.
Please backport to 1.20 and 1.19.
> Change wording around prometheus plugin

- monitor.html.md.erb
Hi docs, this PR is to document the Healthwatch v2 Prometheus and Grafana integration. 
Please cherry-pick this back to 1.19 and 1.20. 
Thanks!
> Add documentation for configuring Prometheus via Healthwatch v2.

- releases.html.md.erb
> Add OAuth for apps to release notes

- releases.html.md.erb
The direct reply-to feature is not supported because the RabbitMQ node names
for on-demand service instances created in >v1.20.0 use long node names.
The long node name includes the BOSH DNS name which comprises
around 150 characters depending on the environment since it includes 2
GUIDS.
The direct reply-to feature creates an Erlang atom which is longer than
the max atom limit of 255 characters since it base 64 encodes the already
long DNS name and adds more characters to it. See https://github.com/rabbitmq/rabbitmq-server/blob/4f43f393bf85e5cd373c84660cc07700fa731e72/deps/rabbit/src/rabbit_channel.erl#L1387-L1393.
* Needs to be added to 1.20.0 - 1.20.3 release notes as well.
> Add direct reply-to feature to known issues

- install-config.html.md.erb
since they changed in https://github.com/pivotal-cf/cf-rabbitmq-release/commit/381c08e107d86bff4a250d47aa40cf1d8a1c27c1#diff-9e30d052c2d5adb5805d5787855ac511c89cfaac75f28320a90203f438808fd8
1.21, 1.20, 1.19, 1.18
> Update pre-stop commands

- install-config.html.md.erb
None. This will be only relevant for v2.x
> Allow tier-1 plugins to be enabled in on-demand in v2.x

- expert-override-config.html.md.erb
The extra colon I believe is causing the title to fail to render in the staging env. This allows the title to be rendered correctly.
This only needs to go into master, for the 2.0 release.
> Fix Title generation in Expert mode doc

- install-config-pp.html.md.erb
The latest patches allowed AMQP to still be accessible when TLS is
enabled, by default.
This should be merged to 1.20 and made live, as it affects the recently-released patches.
> 1.20: Clarification about non-SSL protocols when TLS enabled

- install-config-pp.html.md.erb
The latest patches allowed AMQP to still be accessible when TLS is
enabled, by default.
This should be merged to 1.21 and made live, as it affects the recently-released patches.
> 1.21: Clarification about non-SSL protocols when TLS enabled

- install-config-pp.html.md.erb
The latest patches allowed AMQP to still be accessible when TLS is
enabled, by default.
This should be merged to master for the upcoming 2.0 release.
> 2.0: Clarification about non-SSL protocols when TLS enabled

- monitor-pp.html.md.erb
- monitor.html.md.erb
- releases.html.md.erb
High level summery:
- Update release notes with metrics breaking changes.
- Change the Metrics sections for both on-demand and pre-provisioned.
More detail:
- two breaking changes in release notes
- bosh system metrics: replace punctuation with "_"
- change name of erlang processes and file descriptor metrics
- remove RabbitMQ server component heartbeat. This metric is no longer
emmitted for the RabbitMQ server component.
- remove detecting and resolving partition section
- link to list of metrics from RabbitMQ core
- link Grafana Overview and Erlang Distribution dashboards
> Metrics breaking changes

- install-config-pp.html.md.erb
The comma causes RabbitMQ fail to boot.
Thanks Robert for spotting this!
All branches
> Fix failing example

- releases.html.md.erb
We bump RabbitMQ since CVEs are addressed.
See https://github.com/rabbitmq/rabbitmq-server/releases/tag/v3.8.15 for more information.
None
> Add release notes for v2.0.1

- releases.html.md.erb
We bump RabbitMQ since CVEs are addressed.
See https://github.com/rabbitmq/rabbitmq-server/releases/tag/v3.8.15 for more information.
None
> Add release notes for v1.21.3

- releases.html.md.erb
1.21. Remove the warning about direct reply to in `1.21.3` release note as it is supported in this release.
> Direct reply to is supported in 1.21.3

- index.html.md.erb
- releases.html.md.erb
Here are the release notes for the upcoming 1.21.4 security patch. I will let you know when this is ready to merge into 1.21. An equivalent for 2.0 is incoming.
Thanks!
> Add 1.21.4 release notes

- monitor.html.md.erb
There is an indentation typo, which makes the configuration not usable.
Please merge to 1.20 and 1.21.
> Fix indentation in monitoring

- releases.html.md.erb
This can be made live whenever is convenient. The bug was present in version 2.0.0, and was fixed in 2.0.1.
> Add known Ruby buildpack issue to release notes for 2.0

- releases.html.md.erb
This can be made live whenever is convenient. The bug was present in versions 1.21.2 and lower, and was fixed in 1.21.3.
> Add known Ruby buildpack issue to release notes for 1.21

- install-config.html.md.erb
- secure-inter-node.html.md.erb
This is for an upcoming feature being released in a 2.0.x patch. Since there are many variables to consider when doing a migration, it's not possible to write a 'one size fits all' instruction manual for the process, so this doc attempts to stay somewhat generic.
It's worth noting that this process will involve app downtime, so I'd appreciate feedback on whether that expectation is clear enough.
Thank you!
> Document migrating from a non-inter-node-TLS cluster to a inter-node-TLS cluster

- monitor.html.md.erb
Hello, 
There will be a follow up PR to this one, to address some of the other issues here, 
https://github.com/pivotal-cf/docs-rabbitmq-pcf/issues/611
Thanks!
Alex
> Metrics names change when ugprading to 2.0

- releases.html.md.erb
since is wasn't clear enough from the release notes.
In tile v1 https://github.com/pivotal-cf/rabbitmq-metrics-release
was used to query metrics from the RabbitMQ Management API.
This includes the queue depth (MessagesReady + MessagesUnacknowledged) of every queue.
See https://github.com/pivotal-cf/rabbitmq-metrics-release/blob/c137bc89e250d7e97b14c5b6bd544fb7aa565e19/src/rabbitmq-metrics/provider/api.go#L311-L327
In tile v2 Prometheus is used to query metrics.
By default, only aggregated metrics are returned.
See https://www.rabbitmq.com/prometheus.html#metric-aggregation.
To enable per queue metrics in tile v2, set prometheus.return_per_object_metrics = true.
None
> Add note that metrics are aggregated in v2

- monitor-pp.html.md.erb
- monitor.html.md.erb
Only relevant for 2.0.
For all 2.0 patches:
- It's possible in pre-provisioned and on-demand to scrape per-object metrics; this PR adds in the example configs for that
For the upcoming 2.0.7 patch:
- It's possible to filter the per-object metrics; this PR adds in the example config for this
I'd like to add something to the 2.0.7 release notes around this but I see that change was reverted for inclusion later once we release; what's the best way to change the upcoming release notes to include this feature?
> Add documentation for per-object metrics collection & filtering

- releases.html.md.erb
Can you please also copy the known issue with TLS 1.2 to the live documentation?
Thanks!
> Document lack of TLS 1.2 support in v2.0.7.

- install-config.html.md.erb
None
Upstream counterpart of https://github.com/pivotal-cf/docs-rabbitmq-pcf/pull/628
> Add instructions to use specific tags in service keys for on-demand

- releases.html.md.erb
We had to bump some dependencies before the actual release. These new release notes match the latest build to be promoted to a release.
No need to merge to other branches.
> Update release notes for 2.0.9

- releases.html.md.erb
For some reason they were listing the wrong set of supported versions.
> Fix supported TAS versions for 2.0.x patches

- releases.html.md.erb
2.1.4 is now ready for release today.
> Finalise 2.1.4 release notes ready for release

- releases.html.md.erb
This issue also impacts tile 2.1. 
We will be releasing an upcoming patch to tile 2.2 and 2.1 to resolve this issue.
> Add known issue for missing syslog drain certificate.

- releases.html.md.erb
In order to ensure compatibility with recent TAS patches, the smoke test app has been upgraded to Ruby ~3.1. This requires a recent ruby-buildpack.
> Require TAS 2.11.16+ due to ruby buildpack support compatibility.

- releases.html.md.erb
In order to guarantee compatibility with newer versions of TAS, the smoke-test app has been upgraded to use Ruby ~3.1. Therefore, a sufficiently recent version of the ruby buildpack is required.
> Add requirement for TAS 2.11.16+ due to ruby-buildpack requirement.

- releases.html.md.erb
Please publish these more complete instructions as soon as possible, customers are experiencing failed upgrades due to incomplete instructions.
> Incomplete instructions published in release notes.

- releases.html.md.erb
Somehow the compatibility matrix didn't get included in the 2.1.6 release notes. Here's a PR to fix this. Thanks!
> Include missing compatibility matrix.

- troubleshoot-instances.html.md.erb
- RabbitMQ for VMs 2.3 is compatible with TAS 3.0+.
- TAS 3.0 removed the ability to configure Log Cache for nozzle ingestion
> Remove references to Log Cache Nozzle ingestion (2.3)

- troubleshoot-instances.html.md.erb
- RabbitMQ for VMs 2.3+ is compatible with TAS 3.0+.
- TAS 3.0 removed the ability to configure Log Cache for nozzle ingestion
Co-authored-by: Andrew Crump <andrew.crump@broadcom.com>
(cherry picked from commit 9dd3fa70e765106df84dca5d15eccd7368a9ea13)
> Remove references to Log Cache Nozzle ingestion

- releases.html.md.erb
Apologies, I forgot to correct the loggregator-agent version when copy-pasting the release notes.
> Fix loggregator agent version.
