pivotal-cf/docs-rabbitmq-pcf

- releases.html.md
> release notes for 1.3.5

- releases.html.md
added the missing downtime warning to 1.4 release
> added warning to 1.4 release about downtime

- index.md.erb
- releases.html.md
added known issues for 1.4.1 and 1.4.2
> 1.4.2 issues

- deploying.md.erb
- index.html.md
- releases.html.md
> This is a update from 1.5.3 to 1.5.4 to accommodate the CVE Stemcell update

- policies.md.erb
> Remove default policy in PCF RMQ 1.6

- partitions.html.md
[#119178569]
Signed-off-by: Chavdar Chernashki <cchernashki@pivotal.io>
> network_partition is configured from UI

- configuring.html.md.erb
[#120749825]
Signed-off-by: Svett Ralchev <sralchev@pivotal.io>
> Add security group information to documentation

- index.html.md.erb
Making a change to the multi-az support line
>  updating support docs for multi-az

- index.html.md.erb
- releases.html.md.erb
Please do not delete this branch when it is merged.
> Update to 1.7.7 for OSS 3.6.6 and Erlang 18.3.4.4

- dont-change-ips.html.md.erb
[#150509721]
Signed-off-by: Andrew Thorburn <athorburn@pivotal.io>
> Add draft of docs about not changing IPs

- index.html.md.erb
> Note metrics bug in known issues

- index.html.md.erb
- releases.html.md.erb
> 1.9.6 release notes

- releases.html.md.erb
- rmq-3611-upgrade.html.md.erb
- add link into the release note
[#150704255]
> Add page about behavior change in memory calculation by rabbit

- index.html.md.erb
- releases.html.md.erb
> Release 1.8.18

- rmq-3611-upgrade.html.md.erb
It also necessary to add the link in the releases note, that are in the previous PR
[#150704254]
> Description of memory calculation for rabbit 3.6.12

- index.html.md.erb
- releases.html.md.erb
- rmq-3611-upgrade.html.md.erb
include in the same PR the documentation update about the change in rmq 3.6.12
> Release 1.7.27

- use.html.md.erb
> Add section on how to create admin service keys

- install-config.html.md.erb
[#150203147]
Signed-off-by: Denise Yu <dyu@pivotal.io>
> Add docs about configuring CF service access

- install-config.html.md.erb
- Changed "IMPORTANT" to "Important" to have consistency between notes.
- Removed some trailing whitespaces
[#150928127]
> Add important note about re-configuring AZs

- index.html.md.erb
- releases.html.md.erb
Security release due to a stemcell cve
> Release version 1.7.28

- install-config.html.md.erb
- troubleshoot.html.md.erb
- Remove old troubleshoot information
[#151166681]
Signed-off-by: Hannes Hoerl <hhoerl@pivotal.io>
> Add information about changing number of nodes

- install-config.html.md.erb
> Add a note on how to check on AZs placement of a service instance

- install-config.html.md.erb
> Add a list of plugins enabled by default

- install-config.html.md.erb
[#150202003,#151367891]
Signed-off-by: Hannes Hoerl <hhoerl@pivotal.io>
> Add federation_management and shovel plugin

- monitor-pp.html.md.erb
- monitor.html.md.erb
> Add new metric to 1.9

- index.html.md.erb
> Add known issue and suggest to ask help to support [1.7]

- index.html.md.erb
> Add known issue and suggest to ask help to support [1.8]

- releases.html.md.erb
> Add known issue and suggest to ask help to support [1.9]

- install-config-pp.html.md.erb
> Add warn that the value need to be base64 encoded [1.10]

- install-config-pp.html.md.erb
> Add warn that the value need to be base64 encoded [1.9]

- install-config-pp.html.md.erb
> Add warn that the value need to be base64 encoded [1.8]

- releases.html.md.erb
Update to the release notes for 1.10.3
> update to v1.10.3

- releases.html.md.erb
Added known issue for problem with special chars in password for admin ui
> known password issue

- releases.html.md.erb
Updated to include known password issue
> update known password issue

- install-config-pp.html.md.erb
[#150544137]
Signed-off-by: Ben Chapman <bchapman@pivotal.io>
> [1.8] Improve configuration example

- install-config-pp.html.md.erb
[#150544137]
Signed-off-by: Ben Chapman <bchapman@pivotal.io>
> [1.9] Improve configuration example

- install-config-pp.html.md.erb
[#150544137]
Signed-off-by: Ben Chapman <bchapman@pivotal.io>
> [1.10] Improve configuration example

- monitor-pp.html.md.erb
- monitor.html.md.erb
> Update docs to include new mem_alarm metric

- index.html.md.erb
- releases.html.md.erb
**Please, contact the RabbitMQ for PCF team before publishing**
The product hasn't gone live yet.
> 152344861 1.7 live

- index.html.md.erb
- releases.html.md.erb
**Please, wait until we publish the product before publishing**
[#152344861]
> Add release notes for 1.8.20

- index.html.md.erb
- releases.html.md.erb
**Please do not publish until version is released**
[#152344861]
Signed-off-by: Scott Muc <smuc@pivotal.io>
> Release notes 1.9.9

- monitor.html.md.erb
- releases.html.md.erb
[#152344861]
This change is safe to be merged and published right away.
Signed-off-by: Scott Muc <smuc@pivotal.io>
> Added missing notes around new metrics awesomeness

- ondemand.html.md.erb
Pre-provisioned (multi-tenant) is managed and operated by the platform
operations team.
[#151852562]
Signed-off-by: Scott Muc <smuc@pivotal.io>
> Fix description of pre-provisioned plans

- index.html.md.erb
- releases.html.md.erb
**Note**: please, wait until we publish to pivnet before making these changes live. We will notify the docs team once that's done.
> Add release notes for 1.7.31

- index.html.md.erb
- releases.html.md.erb
**Note**: please, wait until we publish to pivnet before making these changes live. We will notify the docs team once that's done.
> Add release notes for 1.9.10

- index.html.md.erb
- releases.html.md.erb
**Note**: please, wait until we publish to pivnet before making these changes live. We will notify the docs team once that's done.
> Add release notes for 1.8.21

- index.html.md.erb
- releases.html.md.erb
**Note**: please, wait until we publish to pivnet before making these changes live. We will notify the docs team once that's done.
> Add release notes for 1.10.7

- index.html.md.erb
- releases.html.md.erb
We will let you know when to publish this as well.
>  Add release notes for 1.8.21

- index.html.md.erb
- releases.html.md.erb
> Add release notes for 1.19.11

- index.html.md.erb
- releases.html.md.erb
Please, if you merge do not make the docs lite yet. We will publish to pivnet soon.
> Add release notes for 1.7.33

- index.html.md.erb
- releases.html.md.erb
Same as before, I'll let you know when to publish the docs.
> Add release notes for 1.8.23

- install-config.html.md.erb
- releases.html.md.erb
> Add information about colocated errands

- index.html.md.erb
- releases.html.md.erb
> Add release notes for 1.10.9

- index.html.md.erb
- releases.html.md.erb
> Add release notes for 1.11.3

- index.html.md.erb
- releases.html.md.erb
[#154207424]
**Please, wait until we publish the tile on pivnet to make these changes available.**
> Add release notes for 1.7.36

- index.html.md.erb
- releases.html.md.erb
[#154207400]
**Please, wait until we make the tile available on pivnet to publish the docs.**
> Add release notes for 1.9.13

- index.html.md.erb
Update to v 1.11 to include new features for 1.11
> update to features

- index.html.md.erb
- npm-debug.log
Removed v 1.11 from our supported PCF versions
> Removed PCF 1.11 as supported version

- index.html.md.erb
- releases.html.md.erb
> Add release noted for 1.11.5

- index.html.md.erb
- releases.html.md.erb
> Add 1.9.14 release notes

- index.html.md.erb
- releases.html.md.erb
> Add 1.7.37 release notes

- index.html.md.erb
- releases.html.md.erb
> Add release notes 1.10.11

- index.html.md.erb
- releases.html.md.erb
Hello docs team,
This PR is for the Stemcell bump which addresses  Spectre vulnerabilities.
> Stemcell bump to address Spectre vulnerabilities.

- index.html.md.erb
- releases.html.md.erb
Hello docs team,
This PR is for the Stemcell bump which addresses  Spectre vulnerabilities.
>  Stemcell bump to address Spectre vulnerabilities.

- index.html.md.erb
- releases.html.md.erb
> Add release notes for 1.11.7

- index.html.md.erb
- releases.html.md.erb
> Add release notes for 1.8.30

- index.html.md.erb
- releases.html.md.erb
> Add release notes for 1.7.39

- index.html.md.erb
- releases.html.md.erb
> Add release notes for 1.9.16

- index.html.md.erb
- releases.html.md.erb
> Add release notes for 1.10.13

- releases.html.md.erb
> Explain why 1.11.6 was withdrawn

- releases.html.md.erb
> Explain why 1.9.15 was withdrawn

- releases.html.md.erb
> Explain why 1.10.12 was withdrawn

- index.html.md.erb
- releases.html.md.erb
[#155459246]
Signed-off-by: Alberto Leal <aleal@pivotal.io>
> Add release notes for 1.11.8

- index.html.md.erb
- releases.html.md.erb
> Add release notes for 1.10.14

- index.html.md.erb
- releases.html.md.erb
> Add release notes for 1.9.17

- index.html.md.erb
- releases.html.md.erb
[#155459241]
Signed-off-by: Alberto Leal <aleal@pivotal.io>
> Add release notes for 1.8.31

- index.html.md.erb
- releases.html.md.erb
> Add release notes for 1.7.40

- troubleshoot-instances.html.md.erb
> Add troublshooting guide for app developers to access the mgt ui

- releases.html.md.erb
> Update release notes saying that errands don't run colocated anymore

- releases.html.md.erb
> Update release notes to include bug fixes

- index.html.md.erb
- releases.html.md.erb
> Add release notes for 1.7.41

- index.html.md.erb
- releases.html.md.erb
> Add release notes for 1.8.32

- install-config.html.md.erb
> Add resource requirements for RMQ nodes

- index.html.md.erb
- releases.html.md.erb
> Add release notes for 1.9.21

- index.html.md.erb
- releases.html.md.erb
> Add release notes for 1.11.12

- index.html.md.erb
- releases.html.md.erb
> Release notes for 1.10.17

- index.html.md.erb
- releases.html.md.erb
> Add release notes for 1.7.42

- install-config-pp.html.md.erb
Add more information about enabling SSL.
[#156339553]
> Mention the consequences of enabling SSL on a previously deployed service

- upgrade.html.md.erb
This is actually Zoe Vance.
@ghanna2017 we are introducing an entirely new upgrade flow than previous. We will likely need to iterate on this section to explain a bit more.
> 156366332 ondemand upgrades

- replicator.html.md.erb
> Update docs to be accurate for how to run replicator

- policies.html.md.erb
> Add information about memory requirements before queues start syncing

- monitor-pp.html.md.erb
> Mention where to find logs with timestamps

- policies.html.md.erb
- upgrade.html.md.erb
Hi Team,
we have added a link to the best practice whenc syncing a queue.
Thanks
> Add a link to best practices for syncing queues

- upgrade.html.md.erb
Migration path updates based on user interview feedback
I also want to give the upward estimate of how much downtime this could entail and clarify what we mean by healthy here
> Zvance patch 1

- index.html.md.erb
- releases.html.md.erb
- stemcell bump 
- cf-cli update
[#157928986]
> Update release notes for 1.12.5

- index.html.md.erb
- releases.html.md.erb
- stemcell bump 
- cf-cli update
[#157928988]
> Update release notes for 1.11.14

- index.html.md.erb
- releases.html.md.erb
- stemcell bump 
- cf-cli update
[#157928981]
> Update release notes for 1.10.19

- upgrade.html.md.erb
> Edits on the upgrade process

- upgrade.html.md.erb
> Remove ambiguous stop RabbitMQ action

- index.html.md.erb
- releases.html.md.erb
Hi docs team,
we have update some packages in this release.
[#158421089]
> Update release notes for 1.12.6

- install-config.html.md.erb
- Use the same list of special chars used for acceptance
[#158718312]
> Update list of special characters supported

- prepare-tls.html.md.erb
- releases.html.md.erb
- use.html.md.erb
[#156800825]
Co-authored-by: Rosie Bloxsom <rbloxsom@pivotal.io>
> Add release notes for 1.13

- modify-apps-tls.html.md.erb
- use.html.md.erb
Also, remarks that the app developer needs to configure the add to use
specific certs
[#158799337]
> Correct snippets of code to use AMQPS

- install-config-pp.html.md.erb
- releases.html.md.erb
For review by @zvance and @ghanna2017 
[#158867393]
> Add deprecation notice for pre-provisioned service

- index.html.md.erb
- releases.html.md.erb
Hi docs team, we're patching our product.
[#158999517]
Co-authored-by: Andrea Nodari <anodari@pivotal.io>
> Update release notes

- index.html.md.erb
- releases.html.md.erb
Hi docs team, we're patching our product.
[#158689233]
Co-authored-by: Andrea Nodari <anodari@pivotal.io>
> Update release notes for 1.11.15

- releases.html.md.erb
> Update release notes for bug #159237162

- releases.html.md.erb
Can we please merge ? I thought we had this link already here
> Update release notes to link to upgrades page

- releases.html.md.erb
> Release 1.13.2

- releases.html.md.erb
> Remove known issue that was fixed in 1.12.5

- releases.html.md.erb
> Remove known issue that is fixed in 1.11.14

- releases.html.md.erb
As it is causing confusion with customers
cc @csterwa @murphe5
> Removing SCS user upgrade note

- releases.html.md.erb
SCS 1.13 known issue. This can go live anytime
@murphe5 can you please review?
> Add 1.13 known issue

- index.html.md.erb
- releases.html.md.erb
> Add release notes for 1.13.3

- index.html.md.erb
- releases.html.md.erb
> Add release notes for v1.12.8

- upgrade.html.md.erb
Can we please push this live ASAP?
Thanks
Zoe
> Fix for upgrade instructions

- _do-not-upgrade.html.md.erb
- upgrade.html.md.erb
> Upgrade from 1.12 to 1.13 simpler with PCF v2.2.6

- releases.html.md.erb
To indicate that it's only for 2.2.6+
> Update warning on upgrades

- releases.html.md.erb
> Release notes for 1.11.17

- turn-pre-provisioned-off.html.md.erb
[#159077163]
Co-authored-by: Diego Lemos <dlresende@pivotal.io>
> Add instructions on how to turn M-T off

- install-config.html.md.erb
- we have had some feedback that it's confusing.  Specifically it looks
like a RabbitMQ configuration option, when in fact it's a description.
- this should probably be cherry-picked to other branches.  I'm happy to do that work, but would like to get agreement on the wording first.
[#160639830]
> Improve description of "plan features"

- releases.html.md.erb
> Release notes for v1.14.0

- releases.html.md.erb
> Add release 1.13.8

- releases.html.md.erb
Release notes for 1.12.10 and a small correction for previous releases.
> Add release 1.12.10

- use.html.md.erb
This commit should go to v1.14, v1.13, and v1.12. I am happy to cherry-pick it if you want to.
> Improve shovelling docs

- install-config.html.md.erb
> Remove beta flags from feature that are no longer beta

- releases.html.md.erb
@ghanna2017 can you please port this back to 1.12 docs as well?
Do you remember anywhere else where we mention waiting for Spring?
> updated note for SCS users

- releases.html.md.erb
> Release notes for 1.13.10

- releases.html.md.erb
> Release notes for 1.12.12

- ondemand.html.md.erb
Can we please backport to 1.13 & 1.14?
Thanks! Zoe
> Update erlang cookie description

- releases.html.md.erb
some have gotten confused about enabling it
> Note for SCS users to configure pre-provisioned RMQ

- ondemand.html.md.erb
> Docs for migrating Pre-Provision to On-Demand

- use.html.md.erb
> Suggest to restart the app instead of restage

- use.html.md.erb
> Document when to use restart instead of restage

- index.html.md.erb
- releases.html.md.erb
> Release notes for 1.12.13

- index.html.md.erb
- releases.html.md.erb
> Release notes for 1.13.11

- index.html.md.erb
- releases.html.md.erb
> Release notes for 1.14.4

- releases.html.md.erb
> Add new "cf tail" functionality to release notes

- index.html.md.erb
- releases.html.md.erb
> Add 1.15.1 release notes

- index.html.md.erb
- releases.html.md.erb
> Add release notes for v1.13.12

- index.html.md.erb
- releases.html.md.erb
> Release notes for 1.12.14

- index.html.md.erb
- releases.html.md.erb
> Add release notes for v1.14.5

- releases.html.md.erb
- troubleshoot.html.md.erb
> Release notes for 1.13.13

- releases.html.md.erb
- troubleshoot.html.md.erb
> Release for 1.14.6

- releases.html.md.erb
- troubleshoot.html.md.erb
> Release 1.15.3

- releases.html.md.erb
- troubleshoot.html.md.erb
> Release notes for 1.12.15

- turn-pre-provisioned-off.html.md.erb
> Explain how to disable pre-provisioned service if using automation

- ondemand.html.md.erb
[#161619252]
Co-authored-by: Feroz Jilla <fjilla@pivotal.io>
> Describe how to export and import policies and parameters

- ondemand.html.md.erb
The comparison seemed to be written from the perspective of pre-provisioned service. Given our current strategy we decided to rewrite some parts of it.
cc @ferozjilla 
@zvance what do you think?
> Update on-demand multitenant comparison table

- monitor-pp.html.md.erb
- monitor.html.md.erb
[#163192196]
These changes would also apply to earlier versions.  Please let us know if you'd like us to submit PRs to cherry-pick the changes.
> Tidy up some errors found in the metrics docs

- releases.html.md.erb
This affect v1.15, v1.14, v1.13 and v1.12.  I'm happy to cherry-pick it to previous versions if that is helpful.
[#163054709]
> Add CVE-2018-1279 as known issue

- index.html.md.erb
- releases.html.md.erb
> Release note for 1.13.14

- index.html.md.erb
- releases.html.md.erb
> 1.14 live 163862556

- index.html.md.erb
- releases.html.md.erb
> Add 1.15.4 release notes

- index.html.md.erb
- releases.html.md.erb
Release notes for 1.13.15
[#164046804]
> Release notes for 1.13.15

- deploying.html.md.erb
- install-config-pp.html.md.erb
- install-config.html.md.erb
Co-authored-by: Feroz Jilla <fjilla@pivotal.io>
> V1.16 recreate all service instances errand

- reference.html.md.erb
- use.html.md.erb
[#161454249]
Co-authored-by: Andrea Nodari <anodari@pivotal.io>
> Update docs after adding BOSH DNS

- install-config.html.md.erb
- releases.html.md.erb
> Add mqtt to list of plugins that can be enabled

- index.html.md.erb
- releases.html.md.erb
1.15.5 is not live on Pivnet yet. We will ping you when it is
> Add 1.15.5 release notes

- index.html.md.erb
- releases.html.md.erb
1.14.8 is not live on Pivnet yet. We will ping you when it is
> Add 1.14.8 release notes

- index.html.md.erb
- releases.html.md.erb
1.13.16 is not live on Pivnet yet, we will ping you when it is.
> Add 1.13.16 release notes

- releases.html.md.erb
please let me know once updated and i will pull the patches
> Removing all releases with RMQ 3.7.7

- index.html.md.erb
- releases.html.md.erb
> Release notes for 1.13.17

- index.html.md.erb
- releases.html.md.erb
> Release notes for 1.14.9

- index.html.md.erb
- releases.html.md.erb
> Release notes for 1.15.6

- index.html.md.erb
- releases.html.md.erb
> Release notes for 1.15.7

- index.html.md.erb
- releases.html.md.erb
> Release notes for 1.14.10

- index.html.md.erb
- releases.html.md.erb
> Release Notes for v1.13.18

- install-config-pp.html.md.erb
- install-config.html.md.erb
> Rename errand to match name in tile UI

- install-config.html.md.erb
- troubleshoot-instances.html.md.erb
- use.html.md.erb
We also noted that a lot of things in `use.html` were outdated and in an
unhelpful order, so we fixed up the things that were in need of
improvement.
[#164757561]
> Add findings from BOSH DNS to docs

- ondemand.html.md.erb
> Update on-demand, pre-provisioned table

- use.html.md.erb
> Clarify BOSH DNS resolution section

- install-config-pp.html.md.erb
[#164697547]
Co-authored-by: Feroz Jilla <fjilla@pivotal.io>
> [pre-provisioned] Update HAProxy ports description

- index.html.md.erb
- releases.html.md.erb
Please don't publish this yet, as the release is not yet out on Pivnet. Thanks!
>  Add 1.16 first minor (1.16.1) release notes

- index.html.md.erb
- releases.html.md.erb
> Add 1.13.19 release notes

- index.html.md.erb
- releases.html.md.erb
> Add 1.14.11 release notes

- index.html.md.erb
- releases.html.md.erb
Please do not merge yet. Will message you once the release is ready on PivNet.
> Add 1.15.8 release notes

- releases.html.md.erb
Please can you apply this change to 1.16, 1.14 and 1.13 also?
> Update to PivNet policy

- releases.html.md.erb
[#165879568]
Co-authored-by: James McNeil <jmcneil@pivotal.io>
> Added known issue for service-metrics in 1.13

- releases.html.md.erb
[#165879568]
Co-authored-by: James McNeil <jmcneil@pivotal.io>
> Added known issue for service-metrics in 1.15

- releases.html.md.erb
[#165879568]
Co-authored-by: Connor Rogers <crogers@pivotal.io>
> Added known issue for service-metrics in 1.14

- index.html.md.erb
Please can you cherry-pick this change to 1.14 and 1.15?
> Recommendation to use on-demand

- releases.html.md.erb
Hi team, please can you cherry pick this change to releases 1.15.8, 1.15.9, 1.14.11, 1.14.12, and 1.16.2 (when published)?
> Known issue with PP broker

- index.html.md.erb
- releases.html.md.erb
Please hold to merge! We will inform you when we are about to release
Thank you!
> 1.14.12 release notes

- index.html.md.erb
- releases.html.md.erb
Please hold to merge! We will inform you when we are about to release
Thank you!
> 1.13.20 release notes

- index.html.md.erb
- releases.html.md.erb
Please do not merge this yet. We will ping you when we are ready on our end
> Add 1.14.13 release notes

- index.html.md.erb
- releases.html.md.erb
Please do not merge this yet. We will ping you once we are ready on our end :)
> Add 1.15.10 release notes

- index.html.md.erb
- releases.html.md.erb
Please do not merge this yet. We will let you know when we are ready!
> 1.16.3 release

- releases.html.md.erb
> Tweaking release date

- install-config.html.md.erb
- use.html.md.erb
[#165424407]
Co-authored-by: James McNeil <jmcneil@pivotal.io>
> Document amqp 1.0

- migration.html.md.erb
- this generalises the move from PP to OD instances
[#163418873]
Co-authored-by: Connor Rogers <crogers@pivotal.io>
> Add developer docs on how to move between instances

- index.html.md.erb
- releases.html.md.erb
Will notify you when we are ready to deploy
> 1.15.11 Release Notes

- index.html.md.erb
- releases.html.md.erb
Will notify when we are ready to release
> 1.16.4 Release Notes

- index.html.md.erb
- releases.html.md.erb
Will notify you when we are ready to deploy
> 1.14.14 release notes

- index.html.md.erb
- releases.html.md.erb
1.17 is our latest minor, set to be released once we have OSL.
Could you make a new 1.17 branch using this PR please? Thanks!
> Added release notes for 1.17.0

- releases.html.md.erb
Please note that we will need this change to also reflect in the product compatibility matrix. Thanks :)
> Advertise 1.15->1.17 upgrade path

- releases.html.md.erb
Hi docs,
We would like to add this known issue to 1.17.0, 1.16.4, 1.16.3. Please can you do that for us?
Thanks,
Greg & @nodo
> Document an issue with management UI and TLS

- index.html.md.erb
- releases.html.md.erb
Hi docs team, please don't make this public yet. Thanks :)
> Add 1.17.1 release notes

- index.html.md.erb
- releases.html.md.erb
Hi docs, please do not make this public yet too. Thank you :)
> Add 1.15.12 release notes

- index.html.md.erb
- releases.html.md.erb
Hi again docs team, please do not make this public yet too. Thanks!
> Add 1.16.5 release notes

- releases.html.md.erb
> Add release notes for 1.15.13

- releases.html.md.erb
> Update versions for patch 1.17.2

- releases.html.md.erb
> Update versions for patch 1.16.6

- install-config.html.md.erb
Co-authored-by: Alex Blease <ablease@pivotal.io>
> Provide explanation for External URL and port range

- monitor-pp.html.md.erb
- monitor.html.md.erb
Co-authored-by: David O'Sullivan <daosullivan@pivotal.io>
> Rename BOSH System Health Metrics to match PCF KPIs.

- index.html.md.erb
- releases.html.md.erb
> Add 1.16.7 release notes

- service-gateway-access.html.md.erb
[#170150274]
Co-authored-by: Grzegorz Tatarzyn <gtatarzyn@pivotal.io>
> Only AMQP is compatible with Service Gateway.

- about.html.md.erb
- install-config-pp.html.md.erb
We noticed a few things incorrect with our docs. We will cherry-pick to the other supported branches.
> Clarify docs around Management over TLS for 1.18

- about.html.md.erb
- install-config-pp.html.md.erb
We noticed a few things incorrect with our docs. We will cherry-pick to the other supported branches.
> Clarify docs around Management over TLS for 1.17

- rolling-upgrade.html.md.erb
Second draft of our rolling upgrade document. 
https://www.pivotaltracker.com/story/show/168948431
> Rolling upgrade 168948431

- rolling-upgrade.html.md.erb
Hi Docs, 
I restored the rolling upgrade branch, as we needed to make some final changes. 
Thank you!
Alex + @edbyford
> Feedback from Ed

- enable-service-gateway.html.md.erb
> Incorporate changes from docs feedback

- enable-service-gateway.html.md.erb
- use.html.md.erb
Adds docs to disable plugin and service gateway access
> Sg 166976316

- releases.html.md.erb
We will inform you when we get OSL and these docs can be released.
> Add release notes for 1.17.7

- install-config.html.md.erb
Could we also please cherry-pick this commit to the 1.15 - 1.18 branches?
[#168450974](https://www.pivotaltracker.com/story/show/168450974)
> Mention randomize_az_placement feature

- about.html.md.erb
- install-config-pp.html.md.erb
- install-config.html.md.erb
These docs are only relevant for the upcoming 1.19 release.
Before merging, let's wait until one of the reviewers approves this PR.
[#168985456]
> Add rabbitmq_prometheus plugin docs

- about.html.md.erb
- install-config-pp.html.md.erb
- releases.html.md.erb
1. Adds release notes to include prometheus and upgrade check feature for 1.19
2. Add documentation for 1.19
> Docs for prometheus and rolling upgrade checks

- releases.html.md.erb
> Add 1.19.2 Release Notes

- install-config.html.md.erb
- releases_1.19.3.html.md
> 1.19.3 release notes

- install-config.html.md.erb
- releases_1.18.8.html.md
> 1.18.8 release notes 1594977269

- releases.html.md.erb
Co-authored-by: Alex Blease <ablease@pivotal.io>
> Release notes for 1.20.0

- deploying.html.md.erb
Hi docs,
Can you please backport this to earlier versions?
Thanks!
> Reduce haproxy instance count to 0 for advanced deployment.

- monitor.html.md.erb
Hi docs team!
I've updated the monitoring recommendations for RabbitMQ disk alerts following https://www.rabbitmq.com/production-checklist.html
Can you please backport this to all currently supported versions of RabbitMQ? Thanks!
- Mirah
> Update monitoring recommendations with recommended disk alerts.

- enable-oauth.html.md.erb
Hi docs, 
Can you please also cherry-pick this back to the 1.20 branch? 
Thanks!
> Add additional documentation for rabbitmq permissions with OAuth.

- monitor.html.md.erb
> Document scrape config for Prometheus

- releases.html.md.erb
> Add v1.20.2 release notes

- releases.html.md.erb
Please check release notes for style of writing, words chosen, etc.
Thank you very much :)
> Add 1.21.0 release notes

- install-config.html.md.erb
We should include this change in 1.19 and 1.20.
> Document VM extensions

- index.html.md.erb
- releases.html.md.erb
- releases_1.20.3.html.md
Please check release notes for style of writing, words chosen, etc.
Thank you very much :)
> 1.20.3 release notes 1606742771

- install-config-pp.html.md.erb
- install-config.html.md.erb
Hi docs,
Please also port this back to previous supported versions (1.21, 1.20, and 1.19). 
Thanks!
> Add documentation on mTLS support.

- faq-pp.html.md.erb
The way it was explained, will lead to a hanging operation where it will eventually fail. The explanation is in the change itself.
This change needs to be back ported to previous branches as well (i.e. 1.20, 1.19, 1.18 etc.).
> Improving instructions with bosh start/stop

- install-config-pp.html.md.erb
- install-config.html.md.erb
- releases.html.md.erb
Will create a similar PR for the 1.20 and the 1.19 branch.
This PR should also include a change to two pictures in the changed sections. I have the pictures with me and will share on slack.
> Add release notes for 1.21.1

- index.html.md.erb
- install-config-pp.html.md.erb
- releases.html.md.erb
Please do not merge yet since the release is not live on Tanzu Net.
> Add 1.20.5 release notes

- index.html.md.erb
- install-config-pp.html.md.erb
- releases.html.md.erb
Please do not merge yet since the release is not live on Tanzu Net yet.
> Add release notes for 1.21.2

- releases.html.md.erb
Please wait before making the changes live as we're going through the OSL process.
[#177536243]
Co-authored-by: Alex Blease <ablease@pivotal.io>
> Update release notes for 2.0.0

- install-config-pp.html.md.erb
Added at request of Support. Does not need forwards-merging, as the 2.0 docs are slightly different and already include this info.
> Added updated detail about overriding server configuration

- index.html.md.erb
- releases.html.md.erb
Separate PR will be made for 2.x release notes.
> Add 1.21.6 release notes

- releases.html.md.erb
Hi, docs! Here are the release notes for 1.21.7. We aim to release on August 27th.
> Add 1.21.7 release notes.

- releases.html.md.erb
Hi docs, here are the release notes for 2.0.5! We aim to have this release published on August 27th.
> Add release notes for 2.0.5

- monitor-pp.html.md.erb
- monitor.html.md.erb
> Update attribute id in monitoring docs

- monitor-pp.html.md.erb
- monitor.html.md.erb
- releases.html.md.erb
Which other branches should this be merged with (if any)? The main branch might need the update to the attribute tag. Will update there also
> Add release note entry for filtered per-object-metrics

- install-config.html.md.erb
- releases.html.md.erb
The changes in install-config.html.md.erb should be cherry picked to master - I'll send in a second PR for this.
Estimated release date is 20th Jan 2022.
> Add release notes for 2.0.9

- releases.html.md.erb
We are preparing to release 2.0.10, it is currently in OSL and we expect it to be available by 18.02.2022
> Release notes for 2.0.10.

- releases.html.md.erb
The release date for this is actually today, apologies for us not getting the PR in sooner. Whenever you find time to review this is fine with us. Thanks!
> Add 2.0.14 release notes

- releases.html.md.erb
- releases_2.0.15.html.md
Bump RabbitMQ version
This is for a CVE fix
Please merge into 2.0 :)
> 2.0.15 release notes 1653389323

- releases.html.md.erb
We're aiming to release this as soon as possible, hopefully today depending on how quickly our CI runs.
> Add release notes for v2.0.16

- install-config.html.md.erb
- use.html.md.erb
Please merge this onto the latest 2.1 branch. 
Many Thanks,
- Alex
> Docs for log cache compatibilty check box

- releases.html.md.erb
Does not require porting to other releases.
> Add known issue for v2.0.11

- index.html.md.erb
- releases.html.md.erb
Estimated release date is 17th August.
Thank you :)
> Add release notes for v2.1.3

- releases.html.md.erb
> Add release note warnings for CVE-2022-37026

- releases.html.md.erb
> Clarify support policy for 2.0.x

- releases.html.md.erb
Thanks for taking care of the docs!
> 2.1.7 release notes.

- releases.html.md.erb
Thanks for taking care of the docs!
> 2.2.1 release notes.

- releases.html.md.erb
Thanks for taking care of the docs.
> 2.2.2 release notes.

- releases.html.md.erb
> Add 2.2.3 release notes.

- releases.html.md.erb
> Add 2.1.9 release notes.

- releases.html.md.erb
Please publish these updated instructions as soon as possible. Thanks!
> Incomplete instructions published in release notes.

- releases.html.md.erb
> Add 2.1.10 release notes.

- releases.html.md.erb
> Add 2.2.4 release notes.

- releases.html.md.erb
> Add release notes for 2.2.5.

- releases.html.md.erb
> Add 2.1.11 release notes.

- install-config.html.md.erb
Please also backport this to 2.1 documentation. Thanks!
> Clarify AZ selection and network latency concerns.

- releases.html.md.erb
> Add 2.1.12 release notes.

- releases.html.md.erb
> Small release note adjustments.

- releases.html.md.erb
> Add service gateway known issue.

- releases.html.md.erb
> Add release notes for 2.3.1.

- releases.html.md.erb
> Add release notes for 2.2.9.

- releases.html.md.erb
> Add release notes for 2.2.10.

- releases.html.md.erb
> Add 2.3.2 release notes.

- releases.html.md.erb
- Small correction to release notes, as we got feedback from Support that the resolved issues was not clear.
- Adding a new known issue.
None
> Update 2.3.2 release notes

- releases.html.md.erb
> Release notes for 2.3.3.

- install-config.html.md.erb
> Document new feature: Audit Logger
